### ISSUE TITLE
Why are we learning about comments?

### ISSUE THREAD

**Issue by jmburges** [learn-co-curriculum/javascript-comments#2]
Two things
1. Why are they learning about comments so early? It'd be nice to let the students get into some coding quickly! Not learn about comments first thing.
2. Show them the errors that happen when you don't do a comment in JS.

**Comment by pletcher** [comment]
So I actually disagree with 1. (not strongly, but a bit): comments are an essential part of coding and working on a team (I know I'm preaching to the choir here). I think the earlier that students learn about and come to embrace comments, the more likely they are to use them. Especially in a dynamic language, comments allow us to encode information about our programs that is otherwise completely opaque (linters depend on them, for example, and short of a tool like Flow, they're the most frictionless way to add some information about function inputs and outputs).

All of those reasons are, of course, out of scope this early in the curriculum. But I wanted this lesson, one, to be a bit of an earbug for students early in the course; and for it to demystify some of the comments that they might see in _our_ code.

Does that seem okay? Happy to discuss/be convinced otherwise :)

5e8d23c
